### ISSUE TITLE
Implement custom `accent-color` in notifications?

### ISSUE THREAD

**Issue by krystian3w** [KatsuteDev/GitHub-Red-Issues#88]
### Feature

```css
li.notifications-list-item:has(:not(.State.State--merged):not(.TimelineItem-badge) > svg.octicon-issue-closed) {
        accent-color: var(--rissue-issue-closed-fg)
}
```

![obraz](https://user-images.githubusercontent.com/35370833/224827676-e4b4c590-3755-4af4-979f-59df0828a673.png)

### Reason

Compatible with Chromium 105+ and maybe in future with Firefox.

P.S. I detected some not locked PR/issues to collaborators only. Example action to improve auto close:

<details> <summary> yml action code </summary>

```yml
name: 'gatekeeper'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: dessant/lock-threads@v3
        with:
          github-token: ${{ github.token }}
          issue-inactive-days: '40'
          exclude-issue-created-before: ''
          exclude-any-issue-labels: ''
          add-issue-labels: ''
          issue-comment: 'This thread was automatically locked because there was no activity after it was closed. Please open a new ticket for related issues.'
          issue-lock-reason: 'resolved'
          pr-inactive-days: '40'
          exclude-pr-created-before: ''
          exclude-any-pr-labels: ''
          add-pr-labels: ''
          pr-comment: ''
          pr-lock-reason: 'resolved'
#         process-only: 'issues'
```

</details>
